<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.4.0.0</Version>
    <Author>Anomaly</Author>
    <Name>Eorzea Timers</Name>
    <Punchline>Create and track personalized timers in FFXIV.</Punchline>
    <Description>A plugin created by someone learning how to make plugins. Not intended for public use. Will be updated frequently.</Description>
    <RepoUrl>https://github.com/anomalousgamer/EorzeaTimers</RepoUrl>
    <Tags>timer;countdown;reminder</Tags>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\LICENSE.md">
      <Link>LICENSE.md</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\repo.json" Link="repo.json" />
  </ItemGroup>
</Project>
